;(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.6.3
(function() {
  var gistId, _ref;

  gistId = ((_ref = window.location.href.match(/gistId=(\d+)/)) != null ? _ref[1] : void 0) || 6286182;

  $.getJSON("https://api.github.com/gists/" + gistId, function(data, status, request) {
    var entryPoint, program;
    entryPoint = "build.js";
    program = data.files[entryPoint].content;
    return Function("ENV", program)({
      files: data.files
    });
  });

}).call(this);

},{}]},{},[1])
;