// Generated by CoffeeScript 1.6.3
(function() {
  var HAMLjr, Tempest, compile, gistId, parser, util, _ref, _ref1;

  _ref = HAMLjr = require('haml-jr'), parser = _ref.parser, compile = _ref.compile, util = _ref.util;

  Tempest = require('./tempest');

  Object.extend(window, Tempest);

  window.styl = require('styl');

  window.HAMLjr = HAMLjr;

  window.parser = parser;

  window.Gistquire = require('./gistquire');

  Gistquire.onload();

  gistId = ((_ref1 = window.location.href.match(/\?gistId=(.*)/)) != null ? _ref1[1] : void 0) || 6286182;

  Gistquire.get(gistId, function(data) {
    var entryPoint, program;
    console.log(data);
    entryPoint = "build.js";
    program = data.files[entryPoint].content;
    return Function("ENV", program)({
      gist: data,
      $root: $('body')
    });
  });

}).call(this);
