// Generated by CoffeeScript 1.6.3
(function() {
  var gistId, _ref;

  Gistquire.onload();

  gistId = ((_ref = window.location.href.match(/gistId=(\d+)/)) != null ? _ref[1] : void 0) || 6286182;

  Gistquire.get(gistId, function(data, status, request) {
    var entryPoint, program;
    console.log(data);
    entryPoint = "build.js";
    program = data.files[entryPoint].content;
    return Function("ENV", program)({
      gist: data,
      $root: $('body'),
      request: request
    });
  });

}).call(this);
