#!/bin/bash
set -e

rm -r gh-pages/*
mkdir -p gh-pages/javascripts

cp -r lib gh-pages/javascripts/
cp build/*.js gh-pages/javascripts

node_modules/.bin/haml-jr < demo/index.haml > gh-pages/index.html
node_modules/.bin/styl -w < style.styl > gh-pages/style.css
