#!/bin/bash
set +e

BUILD=gh-pages

rm -r $BUILD/*

set -e
mkdir -p $BUILD/javascripts

cp -r lib $BUILD/javascripts/
cp dist/*.js $BUILD/javascripts

node_modules/.bin/coffee -co $BUILD/javascripts demo/*.coffee

node_modules/.bin/browserify $BUILD/javascripts/env.js -i coffee-script > $BUILD/javascripts/envweb.js
node_modules/.bin/browserify $BUILD/javascripts/loader.js -i coffee-script > $BUILD/javascripts/loaderweb.js

node_modules/.bin/haml-jr -H < demo/index.haml > $BUILD/index.html
