#!/bin/bash
set +e

BUILD=gh-pages

rm -r $BUILD/*

set -e
mkdir -p $BUILD/javascripts

cp -r lib $BUILD/javascripts/
cp dist/*.js $BUILD/javascripts

node_modules/.bin/coffee -co $BUILD/javascripts demo/*.coffee

node_modules/.bin/browserify $BUILD/javascripts/browser.js -i coffee-script > $BUILD/javascripts/web.js

node_modules/.bin/haml-jr < demo/index.haml > $BUILD/index.html
node_modules/.bin/styl -w < demo/style.styl > $BUILD/style.css
